### ISSUE TITLE
Error message SedInConnect Ubuntu

### ISSUE THREAD

**Issue by BayensM** [HydrogeomorphologyTools/SedInConnect_2.3#1]
Hello everyone,

I would like to use the SedInConnect application to compute sediment connectivity of alpine catchment. With the help of one colleague, We install it on Ubuntu. However after many tries, I have always the same error messages : 

sh: 1: mpiexec: not found
Traceback (most recent call last):
  File "<string>", line 2361, in OK_rw_conn_outlet
  File "<string>", line 698, in [CavalliConnectivityout]

Is anyone who can help me to solve the problem?
Many thanks,

Bayens Mathilde

Mathilde.Bayens@unil.ch
PhD student

**Comment by HydrogeomorphologyTools** [comment]
Hi, thanks for opening the issue, since it’s the first issue regarding SedInConnect on Linux, it’s worth contextualizing the software structure and the possible solutions.
The error itself is straightforward and is “mpiexec: not found” which means that MPICH or openMPI are either not installed or the path to the binaries has not been set properly.  SedInConnect infact makes several calls to TauDEM functions for some of the processing, TauDEM (a fantastic suite for hydrological analysis, free and open source software) in turn, in order to speed up and distribute processing threads, makes use of MPI for parallel computation. TauDEM depends also on GDAL functions for raster and vector data analysis.
It really depends on how deep you want to go down the rabbit hole of complexity, but, generally speaking I have in mind three ways of tackling the issue, and, increasing the option complexity they are: 
1-	Install a Windows Virtual Machine with 64 bit operating system better if you configure a shared folder between the two Oss for processing/saving and reading files. As an example a virtual box could do for the job (https://www.oracle.com/it/virtualization/technologies/vm/downloads/virtualbox-downloads.html ) You have then to install a Windows OS (e.g., using an ISO image).
Install Taudem (latest installer available here: https://github.com/dtarb/TauDEM/releases/download/v5.3.7/TauDEM537_setup.exe ), at the same page you can find the dependencies: https://hydrology.usu.edu/taudem/taudem5/downloads.html like visual C++. TauDEM complete installer will take care of installing its dependencies like MPI, GDAL
Download and run SedInConnect (https://github.com/HydrogeomorphologyTools/SedInConnect_2.3/releases/tag/SedInConnect_2.3 ) go for the 64 bit version. In the Virtual machine I would suggest setting the RAM amount about at least 20-30x the input raster dimension (200 MB raster -> 4-6 GB RAM)

2-	Instead of using a GUI solution, go for the Python scripts available here: https://github.com/HydrogeomorphologyTools/Sediment-Connectivity-and-Surface-Roughness-python-scripts you need to install (like pip install) only the few non default libraries imported at the beginning of the script (osgeo-> gdal, numpy and few others). At the beginning of the script you set the file paths and the parameters and you’re good to go. This has the great advantage of flexibility letting you insert the processing into a wider computational framework of process rapidly a number of files in batch mode. The available scripts are 2: one for computing surface roughness and the other for Sediment Connectivity computation in respect to a selected (polygon shapefile) target. You can use the computed weighting factor from the roughness script as an input weighting factor in sediment connectivity script. All the details can be found at the above-mentioned GitHub link.

3-	The hard mode.
GDAL dependencies should be fine if you have already installed QGis for example. As it was previously introduced SedInConnect needs TauDEM in order to work, and, if I recall correctly, there is not a straightforward install for TauDEM in Linux. There is an install script that might work and there is also the standard way which means compiling it from source. I noticed things have improved a bit but generally speaking you can expect minor errors in the compiling procedure. To overcome these errors, you need either to modify some imports of some variables. The best way of tackling the issue in my opinion is from here: https://gis.stackexchange.com/questions/265800/installing-taudem-in-linux the page is full of links to the instructions, to the main errors, to the install script and to the suggestion of using TauDEM 5.3.8 tag rather than the develop branch.

You can test whether TauDEM is working properly (combined with MPI processing) by running one of the scripts you can find here: https://hydrology.usu.edu/taudem/taudem5/TauDEM53CommandLineGuide.pdf 
For example if you digit (in the command prompt or terminal) "PitRemove", without the quotes, it should recognize it as a command and even without an input file it should list the available options. The same way if you digit "mpiexec" it should answer that no executable files ha been provided and finally if you digit "mpiexec -n 8 PitRemove"  even without input/output files, it should simply provide 8 times the options message. If this occurs MPI and TauDEM are properly installed and the paths are visible in the system.


Anyway, I would recommend the first solution for a focus on obtaining IC and analyzing it in your case.
Solution 3 in particular is prone to long debugging commitment. And even if working we may have to recompile the binary for the exact Linux version you're using. The debugging phase for making TauDEM and MPI work might help gaining confidence with compiling code and setting un dependencies … system paths and calls and other beautiful and intriguing things for which I love PCs (they make you feel a hero when you finally make the things work!) … but I recognize it might distract you from obtaining IC in a reasonable amount of time. Finally as a side note, messing up with MPI might lead to malfunctioning of some fundamental libraries like libc for example.

Good luck and please, Keep us updated on the progress!

Take care,

Stefano … together with Alessandro and Marco

**Comment by BayensM** [comment]
Hello Stefano,

Thanks so much for your quick and detailed answer. 
I installed an Windows Virtual machine on which I have just installed the Taudem Package and all other necessary files from your 1st proposition. From the command, it looks that the mpi and D8FlowDir are correctly installed (see below the command lines that I get) but I still get the same error message than before .... 

Command lines:
**C:\Users\Aurélien>mpiexec**
Microsoft MPI Startup Program [Version 7.1.12437.25]

Launches an application on multiple hosts.
Usage:

    mpiexec [options] executable [args] [ : [options] exe [args] : ... ]
    mpiexec -configfile <file name>

Common options:
-n <num_processes>
-env <env_var_name> <env_var_value>
-wdir <working_directory>
-hosts n host1 [m1] host2 [m2] ... hostn [mn]
-cores <num_cores_per_host>
-lines
-debug [0-3]
Examples:
    mpiexec -n 4 pi.exe
    mpiexec -hosts 1 server1 master : -n 8 worker
For a complete list of options, run mpiexec -help2
For a list of environment variables, run mpiexec -help3

You can reach the Microsoft MPI team via email at askmpi@microsoft.com

**C:\Users\Aurélien>D8Flowdir**
Error: To run this program, use either the Simple Usage option or
the Usage with Specific file names option
Simple Usage:
 D8Flowdir <basefilename>
Usage with specific file names:
 D8Flowdir -fel <demfile>
-sd8 <slopefile> -p <angfile> [-sfdr <flowfile>]
<basefilename> is the name of the raw digital elevation model
<demfile> is the pit filled or carved DEM input file.
<slopefile> is the slope output file.
<pointfile> is the output d8 flow direction file.
[-sfdr <flowfile>] is the optional user imposed stream flow direction file.
The following are appended to the file names
before the files are opened:
fel    carved or pit filled input elevation file
sd8    D8 slope file (output)
p   D8 flow direction output file


THEN I also try with the toolbox "Connectivity index (Cavalli et al. 2013)" on ArcMap. I installed the toolbox successfully but I have an error message about the DInfFlowDir computation. (By running only the "D-infinity Flow Direction" toolbox I also have the same kind of error.... Do you have any idea of from where this error comes ? 

**Erro message:**
Start Time: Wed Feb  9 16:54:26 2022
Running script DinfFlowDir...
Failed script DinfFlowDir...

Traceback (most recent call last):
  File "C:\Program Files\TauDEM\TauDEM5Arc\DinfFlowDirection.py", line 14, in <module>
    fel = str(desc.catalogPath)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 12: ordinal not in range(128)

Failed to execute (D-Infinity Flow Directions).
Failed at Wed Feb  9 16:54:26 2022 (Elapsed Time: 0,06 seconds)
Failed to execute (ConnectivityIndex).
Failed at Wed Feb  9 16:54:28 2022 (Elapsed Time: 3,37 seconds)



Thanks again for your help!
Mathilde

**Comment by HydrogeomorphologyTools** [comment]
Hi Mathilde,
the error seems to be raised by the use of special characters and is likely to be related to TauDEM.
In particular, the reported error u'\xe9' is related to the letter "é" of the file path (better if you remove the word "Aurélien" from the file path).
I suggest working with simple path names avoiding both spaces and special characters (this is generally a good recommendation for any software).

Try to work on a simple folder like "C:/ test" and SedInConnect should be working fine now.

**Comment by BayensM** [comment]
Yes in fact that was the main problem ... for the SedInConnect and the toolbox ! 
It is working well now :) Thanks so much !

**Comment by HydrogeomorphologyTools** [comment]
Great to hear that! Well done. 
I'll proceed with marking this issue as closed/resolved then.

Stefano
