### ISSUE TITLE
Nodata in IC raster

### ISSUE THREAD

**Issue by hafez-ahmad** [HydrogeomorphologyTools/SedInConnect_2.3#2]
Thank you for making this. I am trying to produce IC using 30 meter DEM. I am getting IC with a lot of No data. Would you please add some suggestion what to do with these things 
![image](https://user-images.githubusercontent.com/20365917/208030519-d86703a9-7122-4177-903c-20d5279f046b.png)

Thank you
Hafez

**Comment by HydrogeomorphologyTools** [comment]
Hi Hafez, thanks for reporting. 
In the first place when I see such patterns I suggest looking at the Input DTM and the input weighting factor (W) rasters as suggested in the GUI, and in the biblio+guidelines.
In particular, the input DTM must be hydrological correct which means without local depressions (you can use a fill sink algorithm to remove local sinks).
Also please check for the absence of No-Data in the input DTM and/or W

**Comment by hafez-ahmad** [comment]
Thank you for you comments. Do suggest any tool for filling or removing local sink?

**Comment by HydrogeomorphologyTools** [comment]
Any fill sink tool of any GIS software could do for the purpose.
To name a few:
-ArcGIS fill tool
-TauDEM fill
-Saga fill sinks (several options here)
-grass r.fill.dir
-WhiteBoxTools fill depressions
...

In case instead, you have no data in your file please refer to QGIS-GSAL native no data change values or Saga or WhiteBos nodata filling tools.
We usually suggest checking also that DTM and W have exact same rows and cols and ref system and origin and cell size. We also suggest using the target option in SedInConnect (needs a polygon that could be the outlet or a polygonal proxy of any target like road or hydronet), since when used this option automatically extracts only the catchment draining to the selected target
